spring:
  storagePath: "/storage"

  liquibase:
    change-log: dbchangelog.yaml
  datasource:
    url: jdbc:h2:~/productservice-db
    username: sa
    password:
server:
  port: 8080
file:
  fileDir: uploads
